#!/usr/bin/env bash
set -euo pipefail

# Stable xtalpi launcher that lets Pi own the tool protocol locally.

PROVIDER="${PROVIDER:-xtalpi-pi-tools}"
MODEL="${MODEL:-deepseek-v4-pro}"

export XTALPI_PI_TOOLS_MAX_TOOLS="${XTALPI_PI_TOOLS_MAX_TOOLS:-24}"
export XTALPI_PI_TOOLS_MAX_TOOL_RESULT_CHARS="${XTALPI_PI_TOOLS_MAX_TOOL_RESULT_CHARS:-20000}"
export XTALPI_PI_TOOLS_MAX_EMPTY_RETRIES="${XTALPI_PI_TOOLS_MAX_EMPTY_RETRIES:-2}"
export XTALPI_PI_TOOLS_MAX_REPAIR_RETRIES="${XTALPI_PI_TOOLS_MAX_REPAIR_RETRIES:-2}"
export XTALPI_PI_TOOLS_MAX_TOTAL_RECOVERIES="${XTALPI_PI_TOOLS_MAX_TOTAL_RECOVERIES:-4}"
export XTALPI_PI_TOOLS_MAX_OUTPUT_TOKENS="${XTALPI_PI_TOOLS_MAX_OUTPUT_TOKENS:-8192}"
export XTALPI_PI_TOOLS_TIMEOUT_MS="${XTALPI_PI_TOOLS_TIMEOUT_MS:-180000}"
export PI_OBSERVATIONAL_MEMORY_PASSIVE="${PI_OBSERVATIONAL_MEMORY_PASSIVE:-true}"

exec pi --provider "$PROVIDER" --model "$MODEL" --thinking off "$@"
